api:
  insecure: true
  dashboard: true
  
certificatesResolvers:
  letsencrypt:
    acme:
      email: "ksenjou@gmail.com"
      storage: "acme.json"
      httpChallenge:
        entryPoint: web

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https 
    transport:
      lifeCycle:
        requestAcceptGraceTimeout: 60
        graceTimeOut: 60
      respondingTimeouts:
        readTimeout: 120
        writeTimeout: 120
        idleTimeout: 240
  websecure:
    address: ":443"
    transport:
      lifeCycle:
        requestAcceptGraceTimeout: 60
        graceTimeOut: 60
      respondingTimeouts:
        readTimeout: 120
        writeTimeout: 120
        idleTimeout: 240
  traefik:
    address: ":8080"

log:
  level: INFO
  format: "json"
accessLog:
  format: json
  fields:
    names:
      StartUTC: drop
  bufferingSize: 100
  filters:
    statusCodes:
      - "300-302"
      - "400-411"
      - "500-524"

providers:
  providersThrottleDuration: 2
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: proxy
    swarmMode: false